(() => {
  "use strict";
  const copy = {
    en: {
      intro: { eyebrow:"A small pause for you", title:"The 3-Minute Rhythm Check", subtitle:"Life can look full from the outside and still feel scattered inside. This short rhythm check helps you notice what may need more nourishment, space, or steadiness in your current season.", text:"", start:"Start the rhythm check", note:"This is a reflective coaching tool, not a diagnosis or medical assessment." },
      cats:["Daily rhythm","Energy","Body & food","Habits","Priorities & boundaries","Self-connection"],
      questions:["My day often gets filled before I have chosen what matters.","I often feel behind before the day has properly started.","I keep going because I can, not because it feels sustainable.","I often call myself lazy when I may actually be depleted.","I notice body signals only when they become hard to ignore.","When life gets full, food becomes comfort, control, reward, escape, or another thing to solve.","I have tried to build certain habits so often that I no longer fully believe myself.","I often think I need more discipline, when I may actually need a smaller step.","Things that are important to me often do not appear in my actual week.","I say yes faster than I can feel whether it is really a yes.","A part of me has become quiet while I have been managing life.","I am tired of trying to figure everything out alone."],
      labels:null,
      reflection:["Which area feels most alive for you right now?","How important does it feel to shift this now?","How possible does change feel right now?","What would feel like a meaningful small shift in the next few weeks?"],
      results:[
        ["Your rhythm may be asking for more listening","You may be moving through life with a lot of capability, but your body’s quieter signals are easy to miss. A helpful next step is not a big plan, but a smaller pause: noticing what your body says before you have to push through.","Once today, pause for 30 seconds and ask: What is my body already telling me?","In coaching, we can explore how to rebuild trust with your body in a gentle, practical way."],
        ["Your rhythm may be asking for steadier nourishment","Food and energy may feel connected to pressure, inconsistency, or overthinking. The next step is not a strict plan, but understanding what actually supports you in real life.","Notice one moment in the day where your energy dips, and ask what kind of support would feel realistic there.","In coaching, we can explore your food rhythm without meal plans, calorie targets, or diet rules."],
        ["Your rhythm may be asking for deeper recovery","You may be getting through your days, but not truly refilling. A useful starting point is noticing where energy leaks, where rest is missing, and what kind of restoration actually works for you.","Choose one small evening or daytime pause that feels genuinely replenishing, not just another task.","In coaching, we can explore what restoration could look like inside your real life."],
        ["Your rhythm may be asking for more space","You may be carrying a lot mentally — not only tasks, but decisions, remembering, planning, adjusting, and holding everything together. The next step may be creating space before adding more solutions.","Write down everything your mind is trying to hold today. Then choose one thing that can be simplified, postponed, or shared.","In coaching, we can look at what is taking up space and where relief may begin."],
        ["Your rhythm may be asking for softer structure","You may not need more discipline. You may need smaller anchors that fit your actual life. The goal is rhythm, not perfection.","Choose one tiny anchor that can happen even on an imperfect day.","In coaching, we can build supportive rhythm without forcing strict routines."],
        ["Your rhythm may be asking for aliveness","Something in you may want more expression, joy, creativity, or room to breathe. This is not extra or silly — it can be part of feeling like yourself again.","Give yourself 10 minutes this week for something with no productivity goal.","In coaching, we can explore how to make space for the parts of you that have been waiting."]],
      scoreResults:[
        {min:12,max:24,title:"Mostly steady",text:"Your rhythm may not feel perfect, but it is not strongly pulling against you right now.",cta:"Your rhythm seems mostly steady right now. There may still be one area worth exploring if it keeps coming back.",button:"Explore a free discovery call",small:"Useful if one pattern stood out and you want to understand it better."},
        {min:25,max:36,title:"Some rhythm strain",text:"You may be functioning, but some parts of your life are starting to cost more energy than they give back.",cta:"Some parts of your rhythm may be asking for attention. This is often the stage where things are not “bad,” but they also do not feel fully right anymore.",button:"Book a free discovery call",small:"We can look at the pattern before it gets heavier."},
        {min:37,max:48,title:"Clear rhythm strain",text:"Your answers suggest that your current rhythm may not fully fit your real life anymore.",cta:"Your answers suggest a clear rhythm strain. You may be functioning, but parts of your energy, habits, body signals, or priorities may not be properly supported.",button:"Book a free discovery call",small:"We can use your Rhythm Check as a starting point for one clear next step."},
        {min:49,max:60,title:"Strong rhythm strain",text:"You may be carrying a lot while still trying to function. This is a good moment to pause and look at the pattern.",cta:"Your rhythm may be carrying too much right now. This does not mean you need to fix everything at once. It means there may be a pattern worth looking at with support.",button:"Book a free discovery call",small:"A 30-minute conversation to find the first useful thread."}
      ],
      ui:{question:"Question",of:"of",reflection:"A little reflection",back:"Back",next:"Continue",see:"See my reflection",optional:"Optional — a few words are enough.",placeholder:"A thought, a feeling, a small possibility…",low:"1 = not true right now",high:"5 = very true right now",low10:"Not very",high10:"Very",first:"A gentle first step",result:"Your reflection",score:"Your score",ctaHead:"Want to explore what your result means for your real life?",ctaText:"In a free discovery call, we can look at what came up and whether coaching feels like a good fit.",book:"Book a free discovery call",disclaimer:"This rhythm check is a reflective coaching tool. It is not a diagnosis, medical assessment, therapy, or a substitute for professional medical or mental health advice."}
    },
    de: {
      intro:{eyebrow:"Ein kleiner Moment für dich",title:"Der 3-Minuten-Rhythmus-Check",subtitle:"Ein sanfter Selbst-Check, um wahrzunehmen, wo deine Energie, dein Körper, deine Gewohnheiten und dein innerer Raum gerade mehr Aufmerksamkeit brauchen.",text:"Von außen kann das Leben voll und funktionierend wirken — und sich innen trotzdem zerstreut oder unausgeglichen anfühlen. Dieser kurze Rhythmus-Check hilft dir wahrzunehmen, wo gerade mehr Nahrung, Raum oder Stabilität entstehen darf.",start:"Rhythmus-Check starten",note:"Dies ist ein reflektierendes Coaching-Tool, keine Diagnose und keine medizinische Einschätzung."},
      cats:["Körpersignale","Essen & Energie","Schlaf & Erholung","Stress & mentale Last","Gewohnheiten & Tagesrhythmus","Selbst-Raum & kreativer Funke"],
      questions:["Ich bemerke meine Bedürfnisse oft erst, wenn sie schon sehr deutlich werden.","Ich gehe häufig über Müdigkeit, Anspannung, Hunger oder emotionale Signale hinweg.","Ich möchte den Signalen meines Körpers mehr vertrauen.","Mein Essrhythmus fühlt sich unregelmäßig, gehetzt oder reaktiv an.","Ich weiß, was meine Energie unterstützt, aber es fällt mir schwer, es regelmäßig zu leben.","Essen kann sich mit Druck, Schuldgefühlen, Regeln oder zu viel Nachdenken vermischen.","Ich wache oft auf, ohne mich wirklich erholt zu fühlen.","Ich habe wenig echte Auszeit, die mich wirklich auffüllt.","Am Abend bleibt oft nicht mehr viel Energie für mich selbst übrig.","Ich fühle mich in zu viele Richtungen gezogen.","Meine Tage fühlen sich oft von Dringlichkeit, den Bedürfnissen anderer oder Reagieren geprägt an.","Mein Kopf plant, merkt sich, sorgt sich oder löst ständig etwas.","Ich beginne unterstützende Routinen, aber sie verlaufen sich oft wieder.","Strikte Pläne funktionieren für mich langfristig nicht wirklich.","Meine Tage würden von ein paar kleinen, verlässlichen Ankern profitieren.","Freude, Kreativität, Spiel oder Ausdruck werden oft zur Seite geschoben.","Ich vermisse einen Teil von mir, der sich früher lebendiger angefühlt hat.","Ich möchte mehr Raum für das, was ich jenseits von Aufgaben, Rollen und Verantwortung bin."],
      labels:["Gar nicht","Ein wenig","Manchmal","Oft","Sehr"],reflection:["Welcher Bereich fühlt sich gerade am lebendigsten oder wichtigsten für dich an?","Wie wichtig fühlt es sich gerade an, hier etwas zu verändern?","Wie möglich fühlt Veränderung gerade für dich an?","Was wäre eine kleine, sinnvolle Veränderung in den nächsten Wochen?"],
      results:[
        ["Dein Rhythmus wünscht sich vielleicht mehr Lauschen","Vielleicht bewegst du dich sehr funktionierend und fähig durch dein Leben, während die leiseren Signale deines Körpers leicht untergehen. Der nächste Schritt muss kein großer Plan sein, sondern ein kleiner Moment des Innehaltens: wahrnehmen, was dein Körper sagt, bevor du wieder darüber hinweggehst.","Halte heute einmal für 30 Sekunden inne und frage dich: Was sagt mein Körper mir eigentlich schon?","Im Coaching können wir erkunden, wie du deinem Körper wieder sanfter und praktischer vertrauen kannst."],
        ["Dein Rhythmus wünscht sich vielleicht stabilere Nahrung","Essen und Energie können sich mit Druck, Unregelmäßigkeit oder zu viel Nachdenken vermischen. Der nächste Schritt ist kein strikter Plan, sondern besser zu verstehen, was dich in deinem echten Leben wirklich unterstützt.","Nimm einen Moment am Tag wahr, an dem deine Energie absinkt, und frage dich, welche Unterstützung dort realistisch wäre.","Im Coaching können wir deinen Essrhythmus anschauen — ohne Ernährungsplan, Kalorienziel oder Diätregeln."],
        ["Dein Rhythmus wünscht sich vielleicht tiefere Erholung","Vielleicht kommst du durch deine Tage, aber füllst dich nicht wirklich wieder auf. Ein guter Anfang ist wahrzunehmen, wo Energie versickert, wo Erholung fehlt und welche Art von Pause dich tatsächlich nährt.","Wähle eine kleine Pause am Abend oder tagsüber, die sich wirklich auffüllend anfühlt — nicht wie eine weitere Aufgabe.","Im Coaching können wir erkunden, wie Erholung in deinem echten Leben aussehen könnte."],
        ["Dein Rhythmus wünscht sich vielleicht mehr Raum","Vielleicht trägst du gerade viel im Kopf — nicht nur Aufgaben, sondern Entscheidungen, Erinnern, Planen, Anpassen und inneres Zusammenhalten. Der nächste Schritt ist vielleicht nicht noch mehr Lösung, sondern zuerst mehr Raum.","Schreibe auf, was dein Kopf heute alles festhält. Dann wähle eine Sache, die einfacher, später oder geteilt werden darf.","Im Coaching können wir anschauen, was gerade so viel Raum nimmt und wo Entlastung beginnen könnte."],
        ["Dein Rhythmus wünscht sich vielleicht weichere Struktur","Vielleicht brauchst du nicht mehr Disziplin. Vielleicht brauchst du kleinere Anker, die wirklich zu deinem Leben passen. Das Ziel ist Rhythmus, nicht Perfektion.","Wähle einen winzigen Anker, der auch an einem unperfekten Tag möglich ist.","Im Coaching können wir unterstützende Rhythmen entwickeln, ohne strikte Routinen zu erzwingen."],
        ["Dein Rhythmus wünscht sich vielleicht mehr Lebendigkeit","Etwas in dir möchte vielleicht mehr Ausdruck, Freude, Kreativität oder Raum zum Atmen. Das ist nicht extra oder nebensächlich — es kann ein Teil davon sein, dich wieder mehr wie dich selbst zu fühlen.","Schenke dir diese Woche 10 Minuten für etwas ohne Produktivitätsziel.","Im Coaching können wir erkunden, wie die Teile von dir wieder Raum bekommen, die lange gewartet haben."]],
      ui:{question:"Frage",of:"von",reflection:"Ein Moment zum Nachspüren",back:"Zurück",next:"Weiter",see:"Meine Reflexion ansehen",optional:"Optional — ein paar Worte genügen.",placeholder:"Ein Gedanke, ein Gefühl, eine kleine Möglichkeit…",low:"Wenig",high:"Sehr",first:"Ein sanfter erster Schritt",result:"Deine Reflexion",ctaHead:"Möchtest du erkunden, was dein Ergebnis für dein echtes Leben bedeutet?",ctaText:"In einem kostenlosen Kennenlerngespräch können wir anschauen, was sichtbar wurde und ob Coaching sich passend anfühlt.",book:"Kostenloses Kennenlerngespräch buchen",disclaimer:"Dieser Rhythmus-Check ist ein reflektierendes Coaching-Tool. Er ist keine Diagnose, keine medizinische Einschätzung, keine Therapie und kein Ersatz für professionelle medizinische oder psychologische Beratung."}
    }
  };
  const lang = document.body.dataset.language === "de" ? "de" : "en", c = copy[lang], app = document.getElementById("app");
  const questionCount = c.questions.length, reflectionCount = c.reflection.length, totalSteps = questionCount + reflectionCount;
  const state = {step:-1, answers:Array(questionCount).fill(null), focus:null, importance:null, possible:null, note:""};
  const esc = s => String(s).replace(/[&<>"]/g, ch => ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[ch]));
  function intro(){app.innerHTML=`<section class="panel intro"><p class="eyebrow">${c.intro.eyebrow}</p><h1>${c.intro.title}</h1><p class="subtitle">${c.intro.subtitle}</p>${c.intro.text?`<p class="intro-copy">${c.intro.text}</p>`:""}<button class="btn" id="start">${c.intro.start} <span aria-hidden="true">→</span></button><small class="note">${c.intro.note}</small></section>`;document.getElementById("start").onclick=()=>{state.step=0;render()}}
  function progress(){const n=state.step+1;return `<div class="progress-wrap"><div class="progress-copy"><span>${state.step<questionCount?`${c.ui.question} ${n} ${c.ui.of} ${questionCount}`:c.ui.reflection}</span><span>${Math.round(n/totalSteps*100)}%</span></div><div class="track" role="progressbar" aria-valuemin="1" aria-valuemax="${totalSteps}" aria-valuenow="${n}"><div class="progress" style="width:${n/totalSteps*100}%"></div></div></div>`}
  function nav(valid,last=false){return `<div class="actions"><button class="btn secondary" data-back>← ${c.ui.back}</button><button class="btn" data-next ${valid?"":"disabled"}>${last?c.ui.see:c.ui.next} <span aria-hidden="true">→</span></button></div>`}
  function slider(value,max,labels){const current=value===null?Math.ceil(max/2):value,fill=(current-1)/(max-1)*100,low=max===5?c.ui.low:c.ui.low10||c.ui.low,high=max===5?c.ui.high:c.ui.high10||c.ui.high;return `<div class="slider-wrap"><output class="slider-value ${value===null?"empty":""}" for="scale">${value===null?"—":value}</output><input class="range-input ${value===null?"unset":""}" id="scale" type="range" min="1" max="${max}" step="1" value="${current}" style="--fill:${fill}%" aria-valuetext="${labels&&value!==null?labels[value-1]:current}">${labels?`<div class="slider-labels" aria-hidden="true">${labels.map((x,i)=>`<span class="${value===i+1?"active":""}">${x}</span>`).join("")}</div>`:`<div class="scale-ends"><span>${low}</span><span>${high}</span></div>`}</div>`}
  function assessment(){const i=state.step, cat=Math.floor(i/(questionCount/c.cats.length));app.innerHTML=`<section class="panel">${progress()}<div class="question-card"><p class="category">${String(cat+1).padStart(2,"0")} · ${c.cats[cat]}</p><h1>${c.questions[i]}</h1><fieldset class="rating"><legend>${c.questions[i]}</legend>${slider(state.answers[i],5,c.labels)}</fieldset>${nav(state.answers[i]!==null)}</div></section>`;bindSlider(v=>state.answers[i]=v,c.labels);bindNav()}
  function reflection(){const r=state.step-questionCount;let input="";if(r===0)input=`<div class="choices">${c.cats.map((x,i)=>`<button class="choice ${state.focus===i?"selected":""}" data-value="${i}" aria-pressed="${state.focus===i}">${x}</button>`).join("")}</div>`;else if(r<3){const val=r===1?state.importance:state.possible;input=slider(val,10)}else input=`<p class="gentle">${c.ui.optional}</p><textarea id="note" maxlength="500" placeholder="${c.ui.placeholder}">${esc(state.note)}</textarea>`;const valid=r===0?state.focus!==null:r===1?state.importance!==null:r===2?state.possible!==null:true;app.innerHTML=`<section class="panel">${progress()}<div class="question-card"><p class="category">${c.ui.reflection}</p><h1>${c.reflection[r]}</h1>${input}${nav(valid,r===reflectionCount-1)}</div></section>`;if(r===0)bindChoice("[data-value]",v=>state.focus=+v);else if(r<3)bindSlider(v=>{if(r===1)state.importance=v;else state.possible=v});else document.getElementById("note").addEventListener("input",e=>state.note=e.target.value);bindNav()}
  function bindChoice(selector,setter){document.querySelectorAll(selector).forEach(b=>b.onclick=()=>{setter(b.dataset.value);render()})}
  function bindSlider(setter,labels){const range=document.querySelector(".range-input"),output=document.querySelector(".slider-value"),next=document.querySelector("[data-next]");if(!range)return;const select=()=>{const value=+range.value;setter(value);output.value=value;output.textContent=value;output.classList.remove("empty");range.classList.remove("unset");range.style.setProperty("--fill",`${(value-1)/(+range.max-1)*100}%`);range.setAttribute("aria-valuetext",labels?labels[value-1]:value);document.querySelectorAll(".slider-labels span").forEach((label,i)=>label.classList.toggle("active",i===value-1));if(next)next.disabled=false};range.addEventListener("input",select);range.addEventListener("pointerup",select)}
  function bindNav(){const back=document.querySelector("[data-back]"),next=document.querySelector("[data-next]");back.onclick=()=>{state.step--;render()};next.onclick=()=>{if(next.disabled)return;state.step++;render()}}
  function winner(){const groupSize=questionCount/c.cats.length,sums=c.cats.map((_,i)=>state.answers.slice(i*groupSize,i*groupSize+groupSize).reduce((a,b)=>a+b,0)),max=Math.max(...sums),tied=sums.map((n,i)=>n===max?i:-1).filter(i=>i>=0);return tied.includes(state.focus)?state.focus:tied[0]}
  function result(){if(c.scoreResults){const total=state.answers.reduce((a,b)=>a+b,0),r=c.scoreResults.find(x=>total>=x.min&&total<=x.max);app.innerHTML=`<section class="result"><header class="result-head"><p class="eyebrow">${c.ui.result}</p><h1>${r.title}</h1><p class="result-category">${c.ui.score}: ${total}</p></header><div class="result-card"><h2>${r.title}</h2><p>${r.text}</p></div><div class="cta"><h2>${c.ui.ctaHead}</h2><p>${r.cta}</p><a class="btn" href="https://app.cal.eu/nokmali/discovery-session">${r.button} <span aria-hidden="true">→</span></a><p class="cta-small">${r.small}</p></div><p class="disclaimer">${c.ui.disclaimer}</p></section>`;return}const i=winner(),r=c.results[i];app.innerHTML=`<section class="result"><header class="result-head"><p class="eyebrow">${c.ui.result}</p><h1>${c.cats[i]}</h1><p class="result-category">${r[0]}</p></header><div class="result-card"><h2>${r[0]}</h2><p>${r[1]}</p><div class="first-step"><strong>${c.ui.first}</strong><p>${r[2]}</p></div></div><div class="cta"><h2>${c.ui.ctaHead}</h2><p class="coaching">${r[3]}</p><p>${c.ui.ctaText}</p><a class="btn" href="https://app.cal.eu/nokmali/discovery-session">${c.ui.book} <span aria-hidden="true">→</span></a></div><p class="disclaimer">${c.ui.disclaimer}</p></section>`}
  function render(){window.scrollTo({top:0,behavior:"smooth"});if(state.step<0)intro();else if(state.step<questionCount)assessment();else if(state.step<totalSteps)reflection();else result();app.focus({preventScroll:true})}
  intro();
})();
